kubesphere/docs.kubesphere.io

src/components/Header.jsx
src/components/TableOfContents/chapter.js
src/layouts/index.css
src/templates/b16-tomorrow-dark.css
src/templates/markdown.css
src/templates/markdown.js

fixed style

---

content/advanced-v1.0.0/zh-CN/infrastructure/nodes.md

update node guide

---

content/advanced-v1.0.0/zh-CN/installation/all-in-one.md
content/advanced-v1.0.0/zh-CN/installation/multi-node.md

update installation guide

---

content/advanced-v1.0.0/zh-CN/installation/storage-configuration.md

1. change the parameters lists sequence
2. split NFS configuration in two parts

Update storage configuration

---

content/advanced-v1.0.0/zh-CN/quick-start/mysql-deployment.md
content/advanced-v1.0.0/zh-CN/storage/pvc.md

update quick start demo1

---

content/advanced-v1.0.0/zh-CN/quick-start/wordpress-deployment.md

update quick start - wordpress

---

content/advanced-v1.0.0/zh-CN/quick-start/jenkinsfile-in-scm.md
content/advanced-v1.0.0/zh-CN/quick-start/jenkinsfile-out-of-scm.md

Signed-off-by: shizgchina <41432506+shizgchina@users.noreply.github.com>

update quick start guide

---

content/advanced-v1.0.0/zh-CN/installation/harbor-installation.md
content/advanced-v1.0.0/zh-CN/quick-start/jenkinsfile-in-scm.md

update harbor and quick start demo6

---

content/advanced-v1.0.0/zh-CN/installation/upgrade.md

update upgrade guide

---

content/advanced-v1.0/zh-CN/installation/all-in-one.md
content/advanced-v1.0/zh-CN/installation/multi-node.md
content/advanced-v1.0/zh-CN/release/release-v101.md

update installation link

---

content/advanced-v1.0/en/quick-start/job-quick-start.md
content/advanced-v1.0/en/storage/pvc.md
content/advanced-v1.0/en/workload/cronjobs.md
content/advanced-v1.0/en/workload/daemonsets.md
content/advanced-v1.0/en/workload/deployments.md
content/advanced-v1.0/en/workload/jobs.md
content/advanced-v1.0/en/workload/statefulsets.md
content/toc_advance_en.json

add workload guide - En

---

content/advanced-v1.0/en/devops/credential.md
content/advanced-v1.0/en/devops/devops-project.md
content/advanced-v1.0/en/devops/pipeline.md
content/advanced-v1.0/en/monitoring/physical-resources.md
content/advanced-v1.0/en/platform-management/account-management.md
content/advanced-v1.0/en/platform-management/role-management.md
content/advanced-v1.0/en/quick-start/hpa.md
content/advanced-v1.0/en/quick-start/jenkinsfile-in-scm.md
content/advanced-v1.0/zh-CN/devops/credential.md
content/advanced-v1.0/zh-CN/devops/devops-project.md
content/advanced-v1.0/zh-CN/devops/pipeline.md
content/advanced-v1.0/zh-CN/installation/harbor-installation.md
content/advanced-v1.0/zh-CN/quick-start/hpa.md
content/toc_advance_en.json

update Harbor guide, add hpa quick start

---

content/advanced-v1.0/en/configuration/image-registry.md
content/advanced-v1.0/en/devops/add-scm.md
content/advanced-v1.0/en/devops/jenkins-agent.md
content/advanced-v1.0/en/installation/harbor-installation.md
content/advanced-v1.0/en/installation/storage-configuration.md
content/advanced-v1.0/en/introduction/advantages.md
content/advanced-v1.0/en/introduction/features.md
content/advanced-v1.0/en/introduction/intro.md
content/advanced-v1.0/en/monitoring/physical-resources.md
content/advanced-v1.0/en/platform-management/account-management.md
content/advanced-v1.0/en/quick-start/hpa.md
content/advanced-v1.0/zh-CN/installation/harbor-installation.md
content/toc_advance_en.json

add devops guide - En, modify introduction - En

---

content/advanced-v1.0/en/installation/all-in-one.md
content/advanced-v1.0/en/installation/multi-node.md
content/advanced-v1.0/en/introduction/advantages.md
content/advanced-v1.0/en/introduction/features.md
content/advanced-v1.0/en/introduction/glossary.md

update introduction and installation guide - En

---

content/advanced-v1.0/en/installation/add-nodes.md
content/advanced-v1.0/en/installation/master-etcd-ha.md
content/advanced-v1.0/en/installation/multi-node.md
content/advanced-v1.0/en/installation/uninstall.md
content/advanced-v1.0/en/introduction/advantages.md
content/advanced-v1.0/en/introduction/features.md

update installation guide - En

---

content/advanced-v1.0/en/installation/intro.md
content/advanced-v1.0/en/platform-management/app-repo.md
content/advanced-v1.0/en/platform-management/workspace-management.md
content/toc_advance_en.json

refine app-repo, installation guide - En

---

content/advanced-v2.0/zh-CN/installation/gitlab-installation.md
content/advanced-v2.0/zh-CN/quick-start/devops-online.md
content/advanced-v2.0/zh-CN/quick-start/harbor-gitlab-devops-offline.md
content/advanced-v2.0/zh-CN/quick-start/source-to-image.md

Signed-off-by: sunzhu <sunzhu@yunify.com>

Update devops & s2i

---

content/advanced-v2.0/zh-CN/quick-start/harbor-gitlab-devops-offline.md
content/advanced-v2.0/zh-CN/quick-start/source-to-image.md

Signed-off-by: soulseen <sunzhu@yunify.com>

Update s2i sample

---

content/advanced-v2.0/zh-CN/quick-start/harbor-gitlab-devops-offline.md

fix broken link

---

content/advanced-v2.0/zh-CN/faq.md

faq: abnormal cpu usage

---

content/advanced-v2.0/zh-CN/quick-start/bookinfo-canary.md

update bookinfo quick start guide

---

content/advanced-v2.0/zh-CN/installation/all-in-one.md
content/advanced-v2.0/zh-CN/quick-start/admin-quick-start.md
content/advanced-v2.0/zh-CN/quick-start/bookinfo-canary.md
content/advanced-v2.0/zh-CN/quick-start/ingress-demo.md

update bookinfo and ingress-demo guide

---

content/advanced-v2.0/zh-CN/faq.md

Signed-off-by: Xin Wang <wileywang@yunify.com>

add qingcloud csi debug guide

---

content/advanced-v2.0/zh-CN/installation/all-in-one.md
content/advanced-v2.0/zh-CN/installation/multi-node.md
content/advanced-v2.0/zh-CN/installation/qingcloud-lb.md
content/advanced-v2.0/zh-CN/installation/storage-configuration.md
content/advanced-v2.0/zh-CN/quick-start/bookinfo-canary.md

update quata and LB installation guide

---

content/advanced-v2.0/zh-CN/quick-start/devops-online.md
content/advanced-v2.0/zh-CN/quick-start/harbor-gitlab-devops-offline.md
content/advanced-v2.0/zh-CN/quick-start/ingress-demo.md

update ingress-demo guide, devops-online guide

---

content/advanced-v2.0/zh-CN/platform-settings/output-fluentd.md

update fluentd description

---

content/advanced-v2.0/zh-CN/faq/faq-storage.md

add storage FAQ guide

---

content/advanced-v2.0/zh-CN/platform-settings/output-kafka.md

add kafka output demo

---

content/advanced-v2.0/zh-CN/platform-settings/log-gathering.md
content/advanced-v2.0/zh-CN/platform-settings/output-kafka.md
content/toc_advance-v2.0_zh-CN.json

add kafka output

---

content/advanced-v2.0/zh-CN/installation/intro.md
content/advanced-v2.0/zh-CN/installation/vars.md
content/advanced-v2.0/zh-CN/platform-settings/output-kafka.md

update GPU description, kafka output guide

---

content/advanced-v2.0/zh-CN/installation/vars.md

update GPU description

---

content/advanced-v2.0/zh-CN/quick-start/ingress-demo.md

update screenshot for ingress-demo

---

content/advanced-v2.0/zh-CN/faq/faq-install.md

Signed-off-by: Xin Wang <wileywang@yunify.com>

add attach volume limit on faq

---

content/advanced-v2.0/zh-CN/installation/gitlab-installation.md
content/advanced-v2.0/zh-CN/installation/multi-node.md
content/advanced-v2.0/zh-CN/quick-start/harbor-gitlab-devops-offline.md

Signed-off-by: soulseen <sunzhu@yunify.com>

update devops & gitlab

---

content/advanced-v2.0/zh-CN/devops/devops-faq.md

add jenkins kubernetes deploy support resource

---

content/advanced-v2.0/zh-CN/devops/devops-faq.md

add sonar faq

---

content/advanced-v2.0/zh-CN/faq/faq-console.md
content/advanced-v2.0/zh-CN/installation/all-in-one.md
content/advanced-v2.0/zh-CN/installation/multi-node.md
content/advanced-v2.0/zh-CN/installation/vars.md

add offline installation

---

content/advanced-v2.0/zh-CN/application/circuit-breaking.md

add circuit breaking guide

---

content/advanced-v2.0/zh-CN/installation/qingcloud-lb.md
content/advanced-v2.0/zh-CN/project-setting/project-gateway.md

update LB plugin

---

content/advanced-v2.0/zh-CN/installation/qingcloud-lb.md
content/advanced-v2.0/zh-CN/project-setting/project-gateway.md

update QingCloud-LB plugin, refine the configuration methods

---

content/advanced-v2.0/zh-CN/installation/qingcloud-lb.md
content/advanced-v2.0/zh-CN/project-setting/project-gateway.md

refine qingcloid-lb and project-gateway guide

---

content/advanced-v2.0/zh-CN/release/release-v201.md

fix typo 2.0.1

---

.travis.yml
content/advanced-v2.0/zh-CN/devops/intro.md
content/advanced-v2.0/zh-CN/platform-settings/app-hosting-official.md
content/toc_advance-v1.0_zh-CN.json
content/toc_advance-v2.0_zh-CN.json

add 2.0 pdf, fix broken link, remove redundant release notes

---

content/advanced-v2.0/zh-CN/multi-tenant/intro.md
content/advanced-v2.0/zh-CN/toolbox/log-search.md

update architechture for logging and IAM

---

gatsby-config.js

Reverts kubesphere/docs.kubesphere.io#366

Revert "fix: Fix swagger url proxy"

---

content/advanced-v2.0/zh-CN/api-reference/monitoring-metrics.md

add cluster metrics

---

content/advanced-v2.0/zh-CN/api-reference/monitoring-metrics.md

add workspace metrics

---

content/advanced-v2.0/zh-CN/api-reference/monitoring-metrics.md

add namespace metrics

---

content/advanced-v2.0/zh-CN/api-reference/monitoring-metrics.md

add workload metrics

---

content/advanced-v2.0/zh-CN/api-reference/api-docs.md
content/advanced-v2.0/zh-CN/api-reference/api-glossary.md
content/advanced-v2.0/zh-CN/api-reference/api-guide.md

update API guide and glossary

---

content/advanced-v2.0/zh-CN/api-reference/monitoring-metrics.md

add component metrics

---

content/advanced-v2.0/zh-CN/api-reference/api-docs.md
content/advanced-v2.0/zh-CN/installation/multi-node.md

update api docs link for jumping to new tap, refine installation guide

---

content/advanced-v2.0/zh-CN/api-reference/api-docs.md
content/advanced-v2.0/zh-CN/devops/devops-admin-faq.md
content/advanced-v2.0/zh-CN/platform-settings/output-kafka.md

refactor output-kafka for logging, update api internal links

---

content/advanced-v2.0/zh-CN/api-reference/api-docs.md
content/advanced-v2.0/zh-CN/installation/all-in-one.md
content/advanced-v2.0/zh-CN/installation/multi-node.md

fix mistaken folder path

---

content/advanced-v1.0/zh-CN/installation/storage-configuration.md
content/advanced-v2.0/zh-CN/infrastructure/components.md

fix typo, fix broken link

---

content/advanced-v2.0/zh-CN/faq/faq-console.md
content/advanced-v2.0/zh-CN/quick-start/ingress-canary.md
content/toc_advance-v2.0_zh-CN.json

add ingress-canary quick start guide, update faq

---

content/advanced-v2.0/zh-CN/faq/faq-install.md

install faq

---

content/advanced-v2.0/zh-CN/workload/s2i-template.md
content/toc_advance-v2.0_zh-CN.json

add s2i template

---

content/advanced-v2.0/zh-CN/faq/faq-install.md

搜索不到，格式的修改

---

content/advanced-v2.0/zh-CN/installation/all-in-one.md
content/advanced-v2.0/zh-CN/installation/install-ks-offline.md
content/advanced-v2.0/zh-CN/installation/install-on-k8s.md
content/advanced-v2.0/zh-CN/installation/intro.md
content/advanced-v2.0/zh-CN/installation/multi-node.md
content/advanced-v2.0/zh-CN/introduction/intro.md
content/advanced-v2.0/zh-CN/platform-settings/app-hosting-github.md
content/advanced-v2.0/zh-CN/platform-settings/app-repo.md
content/advanced-v2.0/zh-CN/quick-start/ingress-canary.md
content/toc_advance-v2.0_zh-CN.json

add installation on k8s, refine docs

---

content/advanced-v2.0/zh-CN/installation/install-on-k8s.md
content/advanced-v2.0/zh-CN/installation/multi-node.md
content/advanced-v2.0/zh-CN/installation/port-firewall.md
content/toc_advance-v2.0_zh-CN.json

add port-firewall.md

---

content/toc_v2.1_zh-CN.json
content/v2.1/zh-CN/installation/all-in-one.md
content/v2.1/zh-CN/installation/components.md
content/v2.1/zh-CN/installation/gitlab-installation.md
content/v2.1/zh-CN/installation/harbor-installation.md
content/v2.1/zh-CN/installation/install-ks-offline.md
content/v2.1/zh-CN/installation/install-on-k8s.md
content/v2.1/zh-CN/installation/intro.md
content/v2.1/zh-CN/installation/multi-node.md
content/v2.1/zh-CN/installation/port-firewall.md
content/v2.1/zh-CN/installation/prerequisites.md
content/v2.1/zh-CN/installation/vars.md
content/v2.1/zh-CN/introduction/intro.md
content/v2.1/zh-CN/release/release-v210.md

init 2.1 docs

---

content/v2.0/en/api-reference/api-docs.md

Signed-off-by: smileycindy <jxncindy@gmail.com>

modify API description

---

content/v2.0/en/introduction/features.md

refined warehouse to image registry

refined warehouse to image registry

---

content/v2.0/en/quick-start/b2i-war.md

Translation of b2i-war.md

---

content/v2.1/zh-CN/system-settings/edit-system-settings.md

Signed-off-by: zhuxiaoyang <sunzhu@yunify.com>

update set ci node

---

content/express/zh-CN/manage-imageregistries.md
content/v1.0/en/configuration/image-registry.md
content/v1.0/en/installation/harbor-installation.md
content/v1.0/zh-CN/configuration/image-registry.md
content/v1.0/zh-CN/installation/harbor-installation.md
content/v1.0/zh-CN/platform-management/image-registry.md
content/v2.0/en/configuration/image-registry.md
content/v2.0/en/installation/harbor-installation.md
content/v2.0/zh-CN/configuration/image-registry.md
content/v2.0/zh-CN/platform-management/image-registry.md
content/v2.1/en/configuration/image-registry.md
content/v2.1/en/installation/harbor-installation.md
content/v2.1/zh-CN/configuration/image-registry.md
content/v2.1/zh-CN/platform-management/image-registry.md

ref https://github.com/kubesphere/kubespray/commit/081094f09e8e5ed1ee0a618d4d7f34f727b19f46

should not set iptables false

---

content/v2.1/zh-CN/devops/jenkins-agent.md

2.1.0 agent tools version

---

content/v2.1/zh-CN/devops/devops-faq.md

update devops deploy support resource version

---

content/toc_v2.1_zh-CN.json
content/v2.1/zh-CN/quick-start/app-store.md

add app-store guide

---

content/v1.0/en/installation/harbor-installation.md
content/v1.0/zh-CN/installation/harbor-installation.md
content/v2.0/en/installation/harbor-installation.md
content/v2.0/zh-CN/installation/harbor-installation.md
content/v2.0/zh-CN/system-settings/push-img-harbor.md
content/v2.1/en/installation/harbor-installation.md
content/v2.1/zh-CN/installation/harbor-installation.md
content/v2.1/zh-CN/system-settings/push-img-harbor.md

Signed-off-by: zhuxiaoyang <sunzhu@yunify.com>

fix harbor image name

---

content/v2.1/zh-CN/devops/jenkins-setting.md
content/v2.1/zh-CN/quick-start/jenkinsfile-out-of-scm.md

add jenkins mail setting docs

---

content/v2.0/zh-CN/installation/install-ks-offline.md
content/v2.0/zh-CN/installation/install-on-k8s.md
content/v2.1/zh-CN/installation/all-in-one.md
content/v2.1/zh-CN/installation/install-on-k8s.md
content/v2.1/zh-CN/installation/intro.md
content/v2.1/zh-CN/installation/prerequisites.md

fix typo for k8s version

---

content/v2.1/zh-CN/release/release-v210.md

update 2.1.0 release note

---

content/v2.1/zh-CN/release/release-v210.md

update 2.1 release notes

---

content/v2.1/zh-CN/installation/install-on-k8s.md

fix mistaken command

---

content/toc_v2.1_en.json
content/v2.1/en/installation/all-in-one.md
content/v2.1/en/installation/intro.md
content/v2.1/en/installation/multi-node.md
content/v2.1/en/installation/pluggable-components.md
content/v2.1/zh-CN/installation/intro.md
content/v2.1/zh-CN/installation/multi-node.md

update 2.1 installation guide - En

---

content/v2.1/zh-CN/api-reference/api-guide.md

Signed-off-by: hongming <talonwan@yunify.com>

update api guide

---

content/v2.1/zh-CN/installation/gitlab-installation.md
content/v2.1/zh-CN/installation/harbor-installation.md
content/v2.1/zh-CN/installation/install-devops.md
content/v2.1/zh-CN/installation/install-openpitrix.md
content/v2.1/zh-CN/platform-management/image-registry.md

update installation guides

---

content/toc_v2.1_zh-CN.json
content/v2.1/zh-CN/api-reference/api-docs.md
content/v2.1/zh-CN/installation/install-grafana.md
content/v2.1/zh-CN/installation/install-logging.md
content/v2.1/zh-CN/installation/ldap-ad.md

update API guide and fix mistaken link

---

content/toc_v2.1_zh-CN.json
content/v2.1/zh-CN/installation/add-storageclass.md
content/v2.1/zh-CN/installation/multi-node.md

add new doc - add-storageclass.md

---

content/v2.1/en/installation/all-in-one.md
content/v2.1/en/installation/harbor-installation.md
content/v2.1/en/installation/intro.md
content/v2.1/en/installation/master-etcd-ha.md
content/v2.1/en/installation/multi-node.md
content/v2.1/en/installation/storage-configuration.md
content/v2.1/en/introduction/intro.md
content/v2.1/zh-CN/quick-start/admin-quick-start.md
content/v2.1/zh-CN/quick-start/app-store.md
content/v2.1/zh-CN/quick-start/b2i-war.md
content/v2.1/zh-CN/quick-start/ingress-demo.md
content/v2.1/zh-CN/quick-start/wordpress-deployment.md
content/v2.1/zh-CN/workload/logs-on-disk.md

update english docs, add video tutorials

---

content/v2.1/zh-CN/system-settings/edit-system-settings.md

refine ci build docs

---

content/v2.1/zh-CN/appendix/install-openebs.md

refine openebs

---

content/toc_v2.1_en.json
content/v2.1/en/introduction/features.md
content/v2.1/en/quick-start/one-click-deploy.md
src/pages/index.js

add one-click-deploy guide

---

content/v2.1/en/devops/credential.md
content/v2.1/en/installation/install-sonarqube.md
content/v2.1/en/introduction/features.md
content/v2.1/en/quick-start/devops-online.md
content/v2.1/en/quick-start/one-click-deploy.md
content/v2.1/zh-CN/quick-start/devops-online.md
content/v2.1/zh-CN/quick-start/hpa.md

add devops tutorials - En

---

content/toc_v2.1_en.json
content/v2.1/en/introduction/features.md
content/v2.1/en/quick-start/b2i-war.md
content/v2.1/zh-CN/quick-start/appstore.md

add binary to image - En

---

content/toc_v2.1_en.json

fix mistaken directory name

---

content/toc_v2.1_zh-CN.json
content/v2.1/zh-CN/installation/all-in-one.md
content/v2.1/zh-CN/installation/complete-installation.md
content/v2.1/zh-CN/installation/multi-node.md

add complete-installation.md

---

content/v2.1/en/introduction/features.md
content/v2.1/en/introduction/what-is-kubesphere.md

refactor what-is-kubesphere and features

---

content/v2.0/en/quick-start/job-quick-start.md
content/v2.1/en/quick-start/job-quick-start.md
content/v2.1/zh-CN/quick-start/ingress-canary.md

update job quick start guide and ingress-canary guide

---

content/v2.1/en/configuration/secrets.md
content/v2.1/en/introduction/features.md
content/v2.1/en/quick-start/source-to-image.md
content/v2.1/zh-CN/quick-start/admin-quick-start.md
content/v2.1/zh-CN/quick-start/ingress-demo.md
content/v2.1/zh-CN/quick-start/wordpress-deployment.md

fix mistaken video link

---

content/v2.1/en/quick-start/canary-release.md
content/v2.1/en/quick-start/ingress-canary.md
content/v2.1/en/quick-start/source-to-image.md

update s2i and canary release quick start guides

---

content/toc_v2.1_en.json
content/v2.1/en/quick-start/devops-online.md
content/v2.1/zh-CN/project-setting/project-gateway.md
content/v2.1/zh-CN/quick-start/ingress-canary.md

refine devops-online.md, fix out-of-date  images in project-gateway.md

---

content/v2.0/zh-CN/installation/sonarqube-jenkins.md

原文档的描述有误，现增加了获取SonarQube内部IP的步骤。

修改配置SonarQube外网访问

---

content/v2.1/en/quick-start/canary-release.md
content/v2.1/en/quick-start/source-to-image.md
content/v2.1/zh-CN/installation/install-on-k8s.md

upload video to install-on-k8s.md, refine source-to-image.md

---

content/v2.1/zh-CN/quick-start/b2i-war.md

fix jar8 jar download url

---

content/toc_v2.1_en.json
content/v2.1/en/quick-start/app-store.md

add app-store quick start guide

---

content/toc_v2.1_en.json
content/toc_v2.1_zh-CN.json
content/v2.1/en/devops/sonarqube.md
content/v2.1/en/installation/install-grafana.md
content/v2.1/en/installation/sonarqube-jenkins.md
content/v2.1/en/quick-start/app-store.md
content/v2.1/en/quick-start/hpa.md
content/v2.1/zh-CN/installation/install-porter.md
content/v2.1/zh-CN/quick-start/ingress-canary.md

add sonarqube-jenkins.md

---

content/toc_v2.1_en.json
content/v2.1/en/installation/ldap-ad.md
content/v2.1/zh-CN/installation/ldap-ad.md

add related tools navigation

---

content/toc_v2.1_en.json
content/toc_v2.1_zh-CN.json
content/v2.1/en/installation/install-grafana.md
content/v2.1/en/installation/install-porter.md
content/v2.1/zh-CN/installation/install-porter.md

refine porter guide, fix mistaken navigation

---

content/toc_v2.1_en.json
content/v2.1/en/installation/complete-installation.md
content/v2.1/en/installation/intro.md
content/v2.1/en/installation/multi-node.md
content/v2.1/en/installation/vars.md
content/v2.1/zh-CN/installation/all-in-one.md
content/v2.1/zh-CN/installation/vars.md

add complete-installation.md and vars.md

---

content/toc_v2.1_en.json
content/v2.1/en/installation/install-gitlab.md
content/v2.1/en/installation/install-harbor.md
content/v2.1/en/installation/intro.md

add harbor and gitlab components

---

content/v2.1/en/installation/install-on-k8s.md
content/v2.1/en/installation/master-ha.md
content/v2.1/en/installation/prerequisites.md
content/v2.1/zh-CN/installation/master-ha.md

refine master-ha.md and prerequisites

---

content/v2.1/en/installation/storage-configuration.md
content/v2.1/zh-CN/installation/storage-configuration.md

update storage-configuration.md - En

---

content/toc_v2.1_zh-CN.json
content/v2.1/zh-CN/configuration/image-registry.md
content/v2.1/zh-CN/installation/install-gitlab.md
content/v2.1/zh-CN/installation/install-harbor.md
content/v2.1/zh-CN/installation/storage-configuration.md
content/v2.1/zh-CN/installation/verify-components.md

fix mistaken steps in harbor guide, add aliyun and tencentcloud csi

---

content/v2.1/en/configuration/image-registry.md
content/v2.1/en/installation/install-harbor.md
content/v2.1/en/installation/install-logging.md
content/v2.1/zh-CN/installation/install-harbor.md
content/v2.1/zh-CN/installation/storage-configuration.md
content/v2.1/zh-CN/quick-start/quick-start-guide.md

refine harbor installation guide - En

---

content/v2.1/en/quick-start/devops-online.md
content/v2.1/en/quick-start/jenkinsfile-out-of-scm.md
content/v2.1/en/quick-start/one-click-deploy.md
content/v2.1/zh-CN/installation/upgrade.md

refine upgrade guide

---

content/v2.1/en/devops/credential.md
content/v2.1/en/introduction/features.md
content/v2.1/en/quick-start/app-store.md
content/v2.1/en/quick-start/b2i-war.md
content/v2.1/en/quick-start/devops-online.md
content/v2.1/en/quick-start/jenkinsfile-out-of-scm.md
content/v2.1/zh-CN/quick-start/app-store.md

update emq charts, fix b2i jar url

---

content/v2.1/en/quick-start/hpa.md

remove outdated description in HPA guide

---

content/toc_v2.1_en.json
content/v2.1/en/devops/credential.md
content/v2.1/en/devops/devops-ci-node.md
content/v2.1/en/devops/pipeline.md
content/v2.1/en/devops/sonarqube.md
content/v2.1/en/installation/sonarqube-jenkins.md
content/v2.1/en/quick-start/devops-online.md
content/v2.1/en/quick-start/jenkinsfile-out-of-scm.md
content/v2.1/zh-CN/quick-start/jenkinsfile-out-of-scm.md

【WIP】update jenkinsfile-out-of-scm guide - En

---

content/toc_v2.1_zh-CN.json
content/v2.1/en/introduction/what-is-kubesphere.md
content/v2.1/en/release/release-v211.md
content/v2.1/zh-CN/installation/upgrade-allinone.md
content/v2.1/zh-CN/installation/upgrade-multi-node.md
content/v2.1/zh-CN/release/release-v211.md

add 2.1.1 release note

---

content/toc_v2.1_en.json
content/toc_v2.1_zh-CN.json
content/v2.1/zh-CN/installation/install-complete-ks-on-k8s.md
content/v2.1/zh-CN/installation/install-on-k8s.md

add install-complete-ks-on-k8s.md

---

content/toc_v2.1_zh-CN.json
content/v2.1/zh-CN/installation/upgrade-allinone.md
content/v2.1/zh-CN/installation/upgrade-multi-node.md
content/v2.1/zh-CN/quick-start/b2i-war.md
content/v2.1/zh-CN/quick-start/bookinfo-canary.md
content/v2.1/zh-CN/quick-start/devops-online.md
content/v2.1/zh-CN/quick-start/hpa.md
content/v2.1/zh-CN/quick-start/ingress-canary.md
content/v2.1/zh-CN/quick-start/source-to-image.md

add videos for quick start guides, refine upgrade guide

---

content/v2.1/zh-CN/devops/jenkins-email.md
content/v2.1/zh-CN/quick-start/jenkinsfile-out-of-scm.md

add jenkins-email.md

---

content/toc_v2.1_zh-CN.json
content/v2.1/zh-CN/developer/helm-developer-guide.md
content/v2.1/zh-CN/developer/s2i-introduce.md
content/v2.1/zh-CN/developer/s2i-template.md

Signed-off-by: zhuxiaoyang <sunzhu@yunify.com>

update s2i doc

---

content/v2.1/en/installation/all-in-one.md
content/v2.1/en/installation/install-on-k8s.md
content/v2.1/en/installation/multi-node.md

update installation guides from 2.1.0 to 2.1.1

---

content/v2.1/en/installation/install-on-k8s.md
content/v2.1/en/installation/prerequisites.md

add CSR signing in prerequisites

---

content/v2.1/zh-CN/developer/s2i-template.md

Compatibility with openshift s2i images

---

content/v2.1/zh-CN/release/release-v211.md

Signed-off-by: hongming <talonwan@yunify.com>

update release note

---

content/v2.1/zh-CN/installation/install-on-k8s-airgapped.md

add "install kubesphere on air gapped Kubernetes cluster"

---

content/v2.1/en/installation/install-on-k8s-airgapped.md
content/v2.1/en/installation/integrate-harbor.md

update air gapped installation

---

content/v2.1/en/installation/install-on-k8s-airgapped.md
content/v2.1/en/installation/integrate-harbor.md

update air gapped installation guides

---

content/toc_v2.1_en.json
content/v2.1/en/developer/s2i-template.md
content/v2.1/en/installation/intro.md
content/v2.1/en/quick-start/admin-quick-start.md
content/v2.1/en/quick-start/app-store.md
content/v2.1/en/quick-start/bookinfo-canary.md

add s2i-template.md

---

content/v2.1/en/installation/install-metrics-server.md
content/v2.1/zh-CN/installation/intro.md

fix mistaken grammar and screenshot

---

content/toc_v2.1_en.json
content/v2.1/en/installation/install-ks-on-linux-airgapped.md
content/v2.1/en/installation/intro.md
content/v2.1/zh-CN/installation/intro.md
content/v2.1/zh-CN/installation/upgrade-allinone.md
content/v2.1/zh-CN/installation/upgrade-multi-node.md

add install-ks-on-linux-airgapped.md

---

content/v2.1/en/installation/install-ks-on-linux-airgapped.md
content/v2.1/en/installation/install-on-k8s-airgapped.md
content/v2.1/en/installation/prerequisites.md

fix the install-ks-on-linux-airgapped for puzzling script

---

content/toc_v2.1_en.json
content/v2.1/en/installation/master-ha.md
content/v2.1/en/installation/upgrade-allinone.md
content/v2.1/en/installation/upgrade-multi-node.md
content/v2.1/zh-CN/installation/master-ha.md

add upgrade guides, update the screenshot of HA installation

---

content/toc_v2.1_en.json
content/toc_v2.1_zh-CN.json
content/v2.1/en/developer/s2i-introduction.md
content/v2.1/zh-CN/developer/s2i-introduction.md
content/v2.1/zh-CN/developer/s2i-template.md

add s2i-introduction.md - En

---

content/toc_v2.1_en.json
content/v2.1/en/installation/install-logging.md
content/v2.1/en/logging/log-query.md

add log query guide - En

---

content/en/api-reference/api-guide.md
content/en/installation/ldap-ad.md
content/en/release/release-v210.md
content/zh-CN/installation/vars.md

add release note 2.1.0, update api guide, remove improper screenshots 

---

content/en/installation/verify-components.md
content/en/troubleshooting/installation.md
content/toc_en.json
content/toc_zh-CN.json
content/zh-CN/introduction/advantages.md
content/zh-CN/introduction/features.md
src/html.js

add troubleshooting guide for installation

---

content/toc_en.json

fix mistaken file name

---

src/templates/markdown.js

fix https://github.com/kubesphere/docs.kubesphere.io/issues/687

fix: Fix markdown edit button

---

content/en/configuration/configmaps.md
content/en/configuration/image-registry.md
content/en/configuration/secrets.md
content/toc_en.json
content/zh-CN/configuration/secrets.md

add json secret guide, update configuration center

---

content/en/configuration/secrets.md

refine secret guide - En

---

content/en/configuration/secrets.md
content/zh-CN/platform-management/workspace-management.md

update project advanced-settings screenshot, fix typo in Secret guide

---

content/zh-CN/appendix/install-openebs.md

fix the mistaken apiversion and taint sequence

---

content/en/configuration/image-registry.md

- Add docs for Harbor Image Registry section to make it more community-friendly
- Fix typo

add docs for Harbor Image Registry section

---

content/en/installation/master-ha.md

- rephrase the wording
- create a table for parameters
A good example of docs to follow is:
https://www.cockroachlabs.com/docs/stable/orchestrate-cockroachdb-with-kubernetes.html#step-2-start-cockroachdb

Make host.ini more clear

---

content/en/installation/all-in-one.md
content/en/installation/multi-node.md
content/toc_en.json
content/zh-CN/installation/all-in-one.md
content/zh-CN/installation/multi-node.md

fix the CentOS version in installation guide

---

content/en/monitoring/alertmanager.md

Signed-off-by: Benjamin <benjamin@yunify.com>

Add Alertmanager Guide

---

content/en/monitoring/notification-manager.md

Signed-off-by: wanjunlei <wanjunlei@yunify.com>
add notification manager user guider

add notification manager user guider

---

content/en/monitoring/notification-manager.md

Signed-off-by: wanjunlei wanjunlei@yunify.com
change group interval of alertmanager

change group interval of alertmanager

---

content/en/installation/add-nodes.md
content/en/installation/complete-installation.md
content/en/installation/install-ks-on-linux-airgapped.md
content/zh-CN/installation/add-nodes.md

Signed-off-by: Sherlock <sherlockxu@yunify.com>

Update node adding desc and remove harbor and gitlab components

---

content/en/monitoring/notification-manager.md

Signed-off-by: wanjunlei wanjunlei@yunify.com
change events to event

change events to event

---

content/en/monitoring/notification-manager.md

Signed-off-by: wanjunlei wanjunlei@yunify.com

delete authPassword namespace of emailconfig

---

content/zh-CN/installation/storage-configuration.md
content/zh-CN/quick-start/quick-start-guide.md

fix broken links

---

content/en/installation/prerequisites.md
content/zh-CN/installation/prerequisites.md

add recommended helm version

---

content/en/faq/telemetry.md

add telemetry

---

content/toc_en.json

update faq in toc

---

content/en/monitoring/notification-manager.md

Signed-off-by: wanjunlei <wanjunlei@yunify.com>

update user guide for sending alert to notification manager

---

content/en/installation/master-ha.md

Signed-off-by: Sherlock113 <sherlockxu@yunify.com>

Add KubeSphere on QingCloud Instance

---

content/en/installation/kubesphere-on-qingcloud-instance.md

Signed-off-by: Sherlock113 <sherlockxu@yunify.com>
Minor wording change for HA installation

Minor wording change for HA installation

---

content/zh-CN/installation/install-on-uk8s.md

Signed-off-by: Haitao Pan <xz@onwalk.net>

add install-on-uk8s.md

---

src/pages/index.js
src/templates/markdown.js

Signed-off-by: liuboaibc <kukudehero@gmail.com>

update doc search

---

content/en/installation/install-on-gke.md
content/en/installation/install-on-k8s-airgapped.md
content/en/installation/install-on-k8s.md
content/zh-CN/installation/install-on-k8s.md

update instllation file address
